name: NekoMaintenance
version: '${version}'
main: NekoMaintenance.Main
authors: [LukeTheNeko]
commands:
  maintenance:
    description: Plugin Maintenance Command by LukeTheNeko
permissions:
  NekoMaintenance.commands:
    default: false
  NekoMaintenance.join:
    default: false