name: NekoMaintenance
version: '${version}'
main: NekoMaintenanceKT.Main
authors: [LukeTheNeko]
commands:
  maintenance:
    description: Plugin Maintenance
permissions:
  NekoMaintenance.commands:
    default: false
  NekoMaintenance.join:
    default: false
