name: NekoMaintenance
version: '1.3.3'
main: NekoMaintenanceKT.Main
authors: [LukeTheNeko]
commands:
  maintenance:
    description: Plugin Maintenance Mode
permissions:
  NekoMaintenance.commands:
    default: false
  NekoMaintenance.join:
    default: false
